# CMake generated Testfile for 
# Source directory: D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests
# Build directory: D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(wtest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Debug/wtest.exe")
  set_tests_properties(wtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;32;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(wtest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Release/wtest.exe")
  set_tests_properties(wtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;32;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(wtest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/MinSizeRel/wtest.exe")
  set_tests_properties(wtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;32;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(wtest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/RelWithDebInfo/wtest.exe")
  set_tests_properties(wtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;32;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
else()
  add_test(wtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(rtest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/rtest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Debug/rtest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(rtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;33;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(rtest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/rtest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Release/rtest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(rtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;33;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(rtest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/rtest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/MinSizeRel/rtest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(rtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;33;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(rtest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/rtest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/rtestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/RelWithDebInfo/rtest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(rtest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;33;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
else()
  add_test(rtest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ftest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/ftest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Debug/ftest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(ftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;34;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ftest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/ftest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Release/ftest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(ftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;34;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ftest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/ftest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/MinSizeRel/ftest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(ftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;34;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ftest "D:/Software/Cmake/bin/cmake.exe" "-DOUT=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/ftest.out" "-DDATA=D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/ftestok.dat" "-DCMD=D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/RelWithDebInfo/ftest.exe" "-P" "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/compare_test.cmake")
  set_tests_properties(ftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;23;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;34;add_compare_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
else()
  add_test(ftest NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(halftest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Debug/halftest.exe")
  set_tests_properties(halftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;35;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(halftest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/Release/halftest.exe")
  set_tests_properties(halftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;35;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(halftest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/MinSizeRel/halftest.exe")
  set_tests_properties(halftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;35;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(halftest "D:/Software/PBRT/PBRT Build/src/ext/ptex/src/tests/RelWithDebInfo/halftest.exe")
  set_tests_properties(halftest PROPERTIES  _BACKTRACE_TRIPLES "D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;35;add_test;D:/Software/PBRT/pbrt-v3/src/ext/ptex/src/tests/CMakeLists.txt;0;")
else()
  add_test(halftest NOT_AVAILABLE)
endif()
